using JobApplier.Domain.Entities;

namespace JobApplier.Domain.Entities;

/// <summary>
/// Represents an AI-generated cover letter.
/// Generated from a parsed CV and a specific job description.
/// </summary>
public class CoverLetter : Entity
{
    /// <summary>
    /// The user who owns this cover letter.
    /// </summary>
    public Guid UserId { get; private set; }

    /// <summary>
    /// The CV this cover letter was generated from.
    /// </summary>
    public Guid CVId { get; private set; }

    /// <summary>
    /// The job description this cover letter targets.
    /// </summary>
    public Guid JobDescriptionId { get; private set; }

    /// <summary>
    /// The final generated cover letter text.
    /// Guaranteed to be 250-350 words (as generated by OpenAI).
    /// </summary>
    public string GeneratedContent { get; private set; }

    /// <summary>
    /// Word count of the generated content.
    /// Tracked for compliance verification (should be 250-350).
    /// </summary>
    public int WordCount { get; private set; }

    /// <summary>
    /// OpenAI API tokens consumed for this generation.
    /// Useful for cost tracking and usage analytics.
    /// </summary>
    public int TokensUsed { get; private set; }

    /// <summary>
    /// The OpenAI model used to generate this cover letter.
    /// e.g., "gpt-4", "gpt-4-turbo"
    /// </summary>
    public string Model { get; private set; }

    /// <summary>
    /// Custom notes or metadata about this generation.
    /// Can be used for A/B testing or version notes.
    /// </summary>
    public string? Notes { get; private set; }

    /// <summary>
    /// Navigation property - User who owns this cover letter
    /// </summary>
    public virtual User? User { get; private set; }

    /// <summary>
    /// Navigation property - CV this letter was generated from
    /// </summary>
    public virtual CV? CV { get; private set; }

    /// <summary>
    /// Navigation property - Job description this letter targets
    /// </summary>
    public virtual JobDescription? JobDescription { get; private set; }

    private CoverLetter() { }

    /// <summary>
    /// Create a new cover letter from OpenAI generation.
    /// </summary>
    public static CoverLetter CreateFromGeneration(
        Guid userId,
        Guid cvId,
        Guid jobDescriptionId,
        string generatedContent,
        int wordCount,
        int tokensUsed,
        string model,
        string? notes = null)
    {
        return new CoverLetter
        {
            UserId = userId,
            CVId = cvId,
            JobDescriptionId = jobDescriptionId,
            GeneratedContent = generatedContent,
            WordCount = wordCount,
            TokensUsed = tokensUsed,
            Model = model,
            Notes = notes
        };
    }

    /// <summary>
    /// Update the generated content (for manual edits or refinements).
    /// </summary>
    public void UpdateContent(string newContent, int newWordCount)
    {
        GeneratedContent = newContent;
        WordCount = newWordCount;
        UpdatedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Add notes to this cover letter.
    /// </summary>
    public void AddNotes(string notes)
    {
        Notes = notes;
        UpdatedAt = DateTime.UtcNow;
    }
}
